class FMVSInventorySizeRule
{
    string Name;
    string ClassName;
    int CargoWidth;
    int CargoHeight;

    void FMVSInventorySizeRule(string name = "", string className = "", int width = 1, int height = 1)
    {
        Name = name;
        ClassName = className;
        CargoWidth = width;
        CargoHeight = height;
    }
};

class FMVSInventorySizeSettings
{
    int ConfigVersion;
    bool Enabled;
    string Note;
    ref array<ref FMVSInventorySizeRule> Rules;

    void FMVSInventorySizeSettings()
    {
        ConfigVersion = 1;
        Enabled = true;
        Note = "Generated by FreezesMVSArmor. Cargo grid changes require rebuilding ModularVestSystem.pbo because itemsCargoSize is config data.";
        Rules = new array<ref FMVSInventorySizeRule>;

        Rules.Insert(new FMVSInventorySizeRule("MVS Chest Rig", "ModularChestRig_Base", 7, 5));
        Rules.Insert(new FMVSInventorySizeRule("MVS Plate Vest", "ModularVestSystem_Base", 8, 6));
        Rules.Insert(new FMVSInventorySizeRule("MVS Heavy Vest", "ModularVestSystem_Heavy", 10, 8));
        Rules.Insert(new FMVSInventorySizeRule("MVS Combat Pack", "MVS_Pack_Base", 7, 10));
        Rules.Insert(new FMVSInventorySizeRule("MVS Raider Pack", "MVS_Assault_Pack_Tan", 8, 10));
        Rules.Insert(new FMVSInventorySizeRule("MVS Sling Pack", "MVS_Sling_Pack_Base", 8, 10));
        Rules.Insert(new FMVSInventorySizeRule("MVS Compact Pack 1", "MVS_Compact_Base", 5, 10));
        Rules.Insert(new FMVSInventorySizeRule("MVS Compact Pack 2", "MVS_Compact_Base_2", 5, 10));
        Rules.Insert(new FMVSInventorySizeRule("MVS Rucksack", "MVS_Rucksack_Base", 10, 12));
        Rules.Insert(new FMVSInventorySizeRule("MVS Combat Pants", "MVS_CombatPants_Base", 7, 5));
        Rules.Insert(new FMVSInventorySizeRule("MVS Combat Shirt", "MVS_CombatShirt_Base", 7, 5));
    }
};
